# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_UserInfo',
            fields=[
                ('Sys_UserInfoID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserResnumber', models.TextField(max_length=100, null=True)),
                ('UserCardNo', models.TextField(max_length=100, null=True)),
                ('UserAccount', models.TextField(max_length=100, null=True)),
                ('UserPwd', models.TextField(max_length=400, null=True)),
                ('UserName', models.TextField(max_length=100, null=True)),
                ('UserSex', models.TextField(max_length=100, null=True)),
                ('InfoBeginTime', models.DateTimeField(null=True)),
                ('Stature', models.FloatField()),
                ('Age', models.IntegerField(null=True)),
            ],
        ),
    ]
