# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 12:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('honghua', '0002_remove_userinfo_cardno'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('cardno', django.db.models.manager.Manager()),
            ],
        ),
    ]
