# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 09:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('honghua', '0004_auto_20180202_0720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('cardno', django.db.models.manager.Manager()),
            ],
        ),
    ]
