# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honghua', '0005_auto_20180204_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='louis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('livein', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
