# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honghua', '0006_louis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
